from deck import *
def main():
    d = Deck()
    print(d)
    print("\n")
    print(d.__repr__())
    d.shuffle_deck()
    print("\n")
    print(d.__repr__())
    print(d)
    d.cut_deck(5)
    print("\n")
    print(d.__repr__())
    print(d)
main()