tunnel: sueca-api
credentials-file: /etc/cloudflared/63686722-dd80-4dc9-b05b-cebe1d9c6d0c.json
origincert: /etc/cloudflared/cert.pem

ingress:
  - hostname: api.suecadaojogo.com
    service: http://gateway:8080
  - hostname: ws.suecadaojogo.com
    service: http://gateway:8080
  - hostname: mqtt.suecadaojogo.com
    service: http://emqx:8083
  - service: http_status:404